# Generated by Django 5.2.10 on 2026-01-19 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_team_created_at_team_created_by_alter_team_captain_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_teams",
                related_query_name="teams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
