# Generated by Django 5.2.10 on 2026-01-14 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0003_match"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournament",
            name="start_date",
        ),
    ]
