# Generated by Django 5.2.10 on 2026-01-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0004_remove_tournament_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
