# Generated by Django 5.2.10 on 2026-01-19 10:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_team_created_at_team_created_by_alter_team_captain_and_more"),
        ("tournaments", "0005_tournament_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="match",
            name="team1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_team1",
                to="teams.team",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="team2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_team2",
                to="teams.team",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="tournaments.tournament",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wins",
                to="teams.team",
            ),
        ),
    ]
