# Generated by Django 5.2.12 on 2026-04-01 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0008_participant"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Participant",
        ),
    ]
