# Generated by Django 5.2.12 on 2026-04-01 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0004_alter_team_created_by_alter_team_tournament"),
        ("tournaments", "0009_delete_participant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="team1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_team1",
                to="teams.team",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="team2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_team2",
                to="teams.team",
            ),
        ),
    ]
