# Generated by Django 5.2.10 on 2026-01-18 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_passwordresettoken"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="f_name",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="l_name",
            new_name="last_name",
        ),
    ]
